def test_login(app, settings):
    app.open_home_page()
    app.session.login(settings.LOGIN, settings.PASSWORD)
    app.search_product.search_product(product_name="гвоздь ондулин")
    app.catalog.quantity(qty="2")
    app.catalog.add_to_cart()
    app.cart_fiz.edit_card(card_number="111111")
    app.cart_fiz.init_order_self()
    app.order_self_fiz.select_base()
    app.order_self_fiz.select_pay_online()
    app.order_self_fiz.input_email(email="info@kluatr.ru")
    app.order_self_fiz.input_phone(phone="(111) 111-11-11")
    app.order_self_fiz.input_username(username="Тест")
    app.order_self_fiz.input_comment(comment="тестовый заказ")
    app.order_self_fiz.submit_order()
    app.thanks.order_link()
    app.session.logout()
